name: Docker 打包构建发布

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取 GitHub 上的代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 登录阿里云容器镜像服务（ACR）
      - name: Login to Alibaba Cloud ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ secrets.ALIYUN_REGISTRY_SERVER }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      # 3. 设置日期和 SHA
      - name: Set tags
        id: tags
        run: echo "sha=${GITHUB_SHA:0:10}" >> $GITHUB_OUTPUT && echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      # 4. 构建并推送 Docker 镜像到阿里云 ACR
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.ALIYUN_REGISTRY_SERVER }}/${{ secrets.ALIYUN_NAMESPACE }}/agentflow:${{ steps.tags.outputs.sha }}-${{ steps.tags.outputs.date }}
            
      # k8s 还没配置
      # 4. 配置 kubectl（连接 K8s 集群）
      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3

      # - name: Configure K8s cluster
      #   run: |
      #     echo "${{ secrets.K8S_CONFIG }}" > ~/.kube/config  # 从 GitHub 密钥读取 K8s 配置

      # 5. 通知 K8s 更新镜像
      # - name: Deploy to K8s
      #   run: |
      #     kubectl set image deployment/nest-app nest-app=your-docker-username/nest-app:latest
      #     kubectl rollout status deployment/nest-app  # 检查更新状态